todowoo/urls.py
from django.contrib import admin
from django.urls import path
from todo import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('signup/',views.signUpUser, name='signUpUser'),
    path('logout/', views.logOutUser, name= 'logOutUser'),
    path('login/', views.logInUser, name= 'logInUser'),
    path('dashboard/',views.dashboard, name='dashboard'),
    path('createtodos', views.createToDos, name='createToDos'),
    path('todo/<int:todo_pk>', views.viewToDo, name='viewToDo'),
    path('todo/<int:todo_pk>/complete', views.completeToDo, name='completeToDo'),
    path('todo/<int:todo_pk>/delete', views.deleteToDo, name='deleteToDo'),
    path('completed/',views.completedToDo, name='completedToDo'),
]

todo/models.py
from time import timezone
from django.db import models
from django.contrib.auth.models import User

class ToDo(models.Model):
    title = models.CharField(max_length=100)
    description=models.TextField(blank=True)
    datecreated= models.DateTimeField(auto_now_add=True)
    datecompleted = models.DateTimeField(null=True, blank=True)
    duedate=models.DateField()
    important = models.BooleanField(default=False)
    completed = models.BooleanField(default=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=None)

    def __str__(self) -> str:
        return self.title

todo/forms.py
from django.forms import ModelForm
from .models import ToDo
class ToDoForm(ModelForm):
    class Meta:
        model = ToDo
        fields = ['title', 'description', 'important', 'duedate','completed',]

todo/views.py
from sqlite3 import IntegrityError
from django.utils import timezone
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.db import IntegrityError
from django.contrib.auth import login, logout, authenticate
from .forms import ToDoForm
from .models import ToDo

# Create your views here.


def home(request):
    return render(request, 'todo/home.html')


def signUpUser(request):
    if request.method == "GET":
        return render(request, 'todo/signUp.html',{'form':UserCreationForm()})
    else:
        if request.POST['password1'] == request.POST['password2']:
            try:
                user = User.objects.create_user(username=request.POST['username'], password=request.POST['password1'])
                user.save()
                login(request, user)
                return redirect('dashboard')
            except IntegrityError:
                return render(request, 'todo/signUp.html',{'form':UserCreationForm(), 'error':'Sorry, that user name is already taken'})
            except ValueError:
                return render(request, 'todo/signUp.html',{'form':UserCreationForm(), 'error':'Please enter a valid username and password'})
        else:
            return render(request, 'todo/signUp.html',{'form':UserCreationForm(), 'error':'Password does not match'})


def logOutUser(request):
    if request.method == 'POST':
        logout(request)
        return redirect('home')


def logInUser(request):
    if request.method == 'GET':
        return render(request, 'todo/login.html',{'form':AuthenticationForm()})
    if request.method == "POST":
        user = authenticate(request=request, username=request.POST['username'], password=request.POST['password'])

        if user is None:
            return render(request, 'todo/login.html',{'form':AuthenticationForm(), 'error':"Username and password do not match"})
        else:
            login(request, user)
            return redirect('dashboard')

def dashboard(request):
    todos = ToDo.objects.filter(user = request.user, datecompleted__isnull=True)
    return render(request, 'todo/dashboard.html', {'todos':todos})

def createToDos(request):
    if request.method == 'GET':
        return render(request, 'todo/createToDo.html',{'form':ToDoForm()})
    else:
        try:
            form = ToDoForm(request.POST)
            newToDo = form.save(commit=False)
            newToDo.user = request.user
            newToDo.save()
            return redirect('dashboard')
        except ValueError:
            return render(request, 'todo/createToDo.html',{'form':ToDoForm(), 'error':'The value entered is not supported'})

def viewToDo(request, todo_pk):
    todo = get_object_or_404(ToDo,pk=todo_pk, user=request.user)
    if request.method == 'GET':
        form = ToDoForm(instance=todo)
        return render(request, 'todo/viewToDo.html', {'todo':todo, 'form':form,})
    if request.method == 'POST':
        try:    
            form  = ToDoForm(request.POST, instance=todo)
            form.save()
            return redirect('dashboard')
        except ValueError:
            return render(request, 'todo/viewToDo.html', {'todo':todo, 'form':form,'error': 'Please check the updates made'})



def completeToDo(request, todo_pk):
    todo = get_object_or_404(ToDo,pk=todo_pk, user=request.user)
    if request.method == 'POST':
        todo.completed = True
        todo.datecompleted = timezone.now()
        todo.save()
        return redirect('dashboard')
    #TODO: to be use after removing the completed checkbox from form and model


def deleteToDo(request, todo_pk):
    todo = get_object_or_404(ToDo,pk=todo_pk, user=request.user)
    if request.method == 'POST':
        todo.delete()
        return redirect('dashboard')

def completedToDo(request):
    todos = ToDo.objects.filter(user = request.user, completed=True).order_by('-datecompleted')
    return render(request, 'todo/completedToDo.html', {'todos':todos})

todo/templates/todo/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">

    <title>Document</title>
</head>
<body style="font-family: 'IBM Plex Mono', monospace;">
        <nav class="navbar navbar-expand-lg" style="background-color: rgb(161, 143, 30);">
            <div class="container-fluid">
                {% if user.is_authenticated %}
                <a class="navbar-brand" href="#">Logged in as {{user.username}}</a>
                {% else %}
                    <a class="navbar-brand" href="#">Todowooooooo...</a>
                {% endif %}
                
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll"
                    aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarScroll">
                    <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'signUpUser' %}">Signup</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'logInUser' %}">Login</a>
                        </li>
                    </ul>
                </div>
                <form class="d-flex" action="{% url 'logOutUser'%}" method="post">
                    {% csrf_token %}
                    <button class="btn btn-outline-success" type="submit">Logout</button>
                </form>
            </div>
        </nav>
        <div class="container">
            {% block content %}{% endblock %}
        </div>
      
</body>
</html>

todo/templates/todo/completedToDo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">

    <title>Your Completed Todos</title>
</head>
<body style="font-family: 'IBM Plex Mono', monospace;">

    <nav class="navbar navbar-expand-lg" style="background-color: rgb(179, 237, 181);">
        <div class="container-fluid">
            <h2>{{user.username}}'s dashboard</h2>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll"
                aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="d-flex" id="navbarScroll">
                <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{%url 'createToDos'%}">Create Todos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link disabled" href="{%url 'completedToDo'%}">See completed ToDos</a>
                    </li>
    
    
                </ul>
                <form class="d-flex" action="{% url 'logOutUser'%}" method="post">
                    {% csrf_token %}
                    <button class="btn btn-danger" type="submit">Logout</button>
                </form>
            </div>
        </div>
    </nav>

    <div class="container" style="margin-top: 40px; padding: 20px;">
        <h2> You have completed {{ todos.count }} todos</h2>
        <ul style="margin-top: 40px;">
            {% for todo in todos %}
            {% if todo.important %}<div class="card w-75" style="background-color: rgb(255, 106, 106);">
                {% else %}<div class="card w-75">
                    {% endif %}
                    <div class="card-body">
                        <h3 class="card-title">{{ todo }}</h3>
                        <p class="card-text">{{todo.datecompleted}}</p> <br>
                        <p class="card-text">{% if todo.description %}{{ todo.description|truncatechars:150 }}{% endif%}</p>

                        <a href="{% url 'viewToDo' todo.id %}" class="btn btn-success">See details</a>
                    </div>
                </div>
                <br><br>
                {% endfor %}
        </ul>
    </div>

</body>
</html>

todo/templates/todo/createToDo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">

    <title>Create ToDos</title>
</head>
<body style="font-family: 'IBM Plex Mono', monospace;">
    <nav class="navbar navbar-expand-lg" style="background-color: rgb(179, 237, 181);">
        <div class="container-fluid">
            <h2>{{user.username}}'s dashboard</h2>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll"
                aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="d-flex" id="navbarScroll">
                <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
                    <li class="nav-item">
                        <a class="nav-link disabled" aria-current="page" href="{%url 'createToDos'%}" role="button">Create Todos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{%url 'completedToDo'%}" role="button">See completed ToDos</a>
                    </li>

                </ul>
                <form action="{% url 'logOutUser' %}" method="post" >
                    {% csrf_token %}
                    <button class="btn btn-outline-danger" type="submit">Logout</button>
                </form>
            </div>
        </div>
    </nav>

    <br><br><br><br>

    <div class="container">
        <h2>Create Todo</h2> 
        {% if error %}
        <div class="alert alert-danger" role="alert">
            <b>{{error}}</b>
        </div>
        {% endif %}
        <div class="form-control">
            <form action="" method="POST">
                {% csrf_token %}
                <!--{{ form.as_p }}-->
                <label for="id_title">Title:</label>
                <input type="text" name="title" maxlength="100" required id="id_title" class="form-control">
            
                <label for="id_description">Description:</label>
                <textarea name="description" cols="40" rows="10" id="id_description" class="form-control"></textarea>
            
                <label for="id_important">Important:</label>
                <input type="checkbox" name="important" id="id_important">
                <br><br>
                <label for="id_duedate">Duedate:</label>
                <input type="date" name="duedate" required id="id_duedate">
                
                <br><br>
                <label for="id_completed">Completed:</label>
                <input type="checkbox" name="completed" id="id_completed">
                <br> <br>
                <button type="submit" class="btn btn-success">Save ToDo</button>
            </form>
        </div>
        
    </div>
    
</body>
</html>

todo/templates/todo/dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">

    <title>Your Dashboard</title>
</head>
<body style="font-family: 'IBM Plex Mono', monospace;">

    <nav class="navbar navbar-expand-lg" style="background-color: rgb(179, 237, 181);">
        <div class="container-fluid">
            <h2>{{user.username}}'s dashboard</h2>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll"
                aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="d-flex" id="navbarScroll">
                <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{%url 'createToDos'%}">Create Todos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{%url 'completedToDo'%}">See completed ToDos</a>
                    </li>
                    
                    
                </ul>
                <form class="d-flex" action="{% url 'logOutUser'%}" method="post">
                    {% csrf_token %}
                    <button class="btn btn-outline-success" type="submit">Logout</button>
                </form>
            </div>
        </div>
    </nav>

    <div class="container" style="margin-top: 40px; padding: 20px;">
        <h2> You have {{ todos.count }} todos to complete </h2>
        <ul style="margin-top: 40px;">
            {% for todo in todos %}
            {% if todo.important %}<div class="card w-75" style="background-color: rgb(255, 106, 106);">
                {% else %}<div class="card w-75">
                {% endif %}
                        <div class="card-body">
                            <h4 class="card-title">{{ todo }}</h4>
                            <p class="card-text">{% if todo.description %}{{ todo.description|truncatechars:150 }}{% endif%}</p>
                            <a href="{% url 'viewToDo' todo.id %}" class="btn btn-success">See details</a>
                        </div>
                    </div>
            <br><br>
            {% endfor %}
        </ul>
    </div>

    
</body>
</html>

todo/templates/todo/home.html
<!DOCTYPE html>
<html lang="en">


<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">

        
    <title>Todowoo</title>
</head>

<body style="font-family: 'IBM Plex Mono', monospace;">
    {% load static %}
    <nav class="navbar navbar-expand-lg" style="background-color: rgb(161, 143, 30);">
        <div class="container-fluid">
            <h2>Todowooooooo...</h2>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll"
                aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarScroll">
                <div class="row justify-content-end">
                    <div class="col-4">
                        <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'signUpUser' %}">Signup</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'logInUser' %}">Login</a>
                        </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </nav>
    
    <div class="container" style="padding: 40px;">
        <p style="padding: 20px;">
            <h1>
                Hi there, wanna keep tab of the lists of tedious tasks that needs to be done? <br>
                Worry not we got your back. Just signup and leave your WOOries behind.
            </h1>
            <h4>
                If you are an existing user, click on login to go to your dashboard.
            </h4>
        </p>
    </div>
</body>


</html>

todo/templates/todo/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">

    <title>Login</title>
</head>
<body style="font-family: 'IBM Plex Mono', monospace;">
    <nav class="navbar navbar-expand-lg" style="background-color: rgb(161, 143, 30);">
        <div class="container-fluid">
            <h2>ToDoWooooooo</h2>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll"
                aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <form class="d-flex" action="{% url 'signUpUser'%}" method="GET">
                {% csrf_token %}
                <button class="btn btn-primary" type="submit">Signup</button>
            </form>
        </div>
    </nav>

    <div class="row justify-content-center mt-5">
        <div class="col-md-5">
            <br><br><br>
            <h1>Login to your account</h1>
            {% if error %}
            <div class="alert alert-danger" role="alert">
                {{error}}
            </div>
            {% endif %}
            <form action="" method="post">
                {% csrf_token %}
                <!--{{form.as_p}}-->
                <div class="form-control">
                    <label for="username">Enter your username</label>
                    <input type="text" class="form-control" name="username" id="username">
                    <br>
                    <label for="password">Enter your password</label>
                    <input type="password" class="form-control" name="password" id="password">

                </div>
                <button type="submit" class="btn btn-primary">Login</button>
            </form>
        </div>
    </div>
    
</body>
</html>

todo/templates/todo/signUp.html
<!DOCTYPE html>
    <head>

        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
            integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">

        <title>User SignUp</title>
    </head>

    <body style="font-family: 'IBM Plex Mono', monospace;">
        <nav class="navbar navbar-expand-lg" style="background-color: rgb(161, 143, 30);">
            <div class="container-fluid">
                <h2>Todowooooooo...</h2>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll"
                    aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="d-flex" id="navbarScroll">
                    <form action="{% url 'logInUser' %}" method="GET">
                        <button type="submit" class="btn btn-primary">Login</button>
                    </form>
                </div>
            </div>
        </nav>

        <div class="row justify-content-center mt-5">
            <div class="col-md-5">
                <h1>SignUp to use ToDoWoo</h1>
                
                {% if error %}
                <div class="alert alert-danger" role="alert">
                    {{error}}
                </div>
                {% endif %}
                
                <form action="" method="post">
                    {% csrf_token %}
                    <!--{{ form.as_p }}-->
                    <div class="form-control">
                        <label for="username">What would like to be called?</label>
                        <input type="text" class="form-control" name="username" id="username" aria-describedby="usernamehelpertxt">
                        <small id="usernamehelpertxt">Please choose a unique username</small>
                    </div>
                    <div class="form-control">
                        <label for="password1">Choose a strong password</label>
                        <input type="password" class="form-control" name="password1" id="password1">
                        
                    </div>
                    <div class="form-control">
                        <label for="password2">Confirm your password</label>
                        <input type="password" class="form-control" name="password2" id="password2">
                    </div>
                    <button type="submit" class="btn btn-primary">SignUp</button>
                </form>
                <br>
                <p>If you have an account then click on Login</p>
            </div>
        </div>
        
    </body>

</html>

todo/templates/todo/viewToDo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">

    <title>{{todo.title}}</title>
</head>
<body style="font-family: 'IBM Plex Mono', monospace;">

    <nav class="navbar navbar-expand-lg" style="background-color: rgb(161, 143, 30);">
        <div class="container-fluid">
            <h2>{{user.username}}'s dashboard</h2>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll"
                aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="d-flex" id="navbarScroll">
                <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{%url 'createToDos'%}">Create Todos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{%url 'completedToDo'%}">See completed ToDos</a>
                    </li>
    
    
                </ul>
                <form class="d-flex" action="{% url 'logOutUser'%}" method="post">
                    {% csrf_token %}
                    <button class="btn btn-danger" type="submit">Logout</button>
                </form>
            </div>
        </div>
    </nav>


    <br><br><br>
    <div class="container">
        <h1>{{todo.title}}</h1>
        {% if error %}
        <div class="alert alert-danger" role="alert">
            {{error}}
        </div>
        {% endif %}
        <div class="form-control">
            <form class="d-flex" action="{% url 'deleteToDo' todo.id %}" method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-outline-danger">Delete</button>
            </form>
            <form class="d-flex" action="{% url 'completeToDo' todo.id %}" method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-outline-success">Complete</button>
            </form>
        </div>
        

        <form action="" method="post" class="form-control">
            {% csrf_token %}
            
            <label for="id_title">Title:</label>
            <input type="text" name="title" maxlength="100"  value="{{todo.title}}" required id="id_title" class='form-control'>
        
            <label for="id_description">Description:</label>
            <textarea name="description" cols="40" rows="10" id="id_description" class='form-control'>{{todo.description}}</textarea>
        
            <label for="id_important">Important:</label>
            <input type="checkbox" name="important" id="id_important" {% if todo.important %}checked{% endif %}> <br>
        
            <label for="id_duedate">Duedate:</label>
            <input type="date" name="duedate" value="{{todo.duedate|date:'Y-m-d'}}" required id="id_duedate" > <br>
        
        
            <!--label for="id_completed">Completed:</label>
            <input type="checkbox" name="completed" id="id_completed"--> <br>
        
        
            <button type="submit" class="btn btn-outline-success">Save</button>
            <!--button type="submit" class="btn btn-outline-danger" onclick="$('#delete').click()">Delete</button-->
            
        </form>
        
    </div>

</body>
</html>